-- MySQL Script generated by MySQL Workbench
-- Thu Dec 25 04:51:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`Pouzivatel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pouzivatel` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `meno` VARCHAR(100) NOT NULL,
  `priezvisko` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `heslo` VARCHAR(255) NOT NULL,
  `telefon` VARCHAR(20) NOT NULL,
  `aktivny` TINYINT(1) NOT NULL DEFAULT 1,
  `obrazok_url` VARCHAR(2048) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Rola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Rola` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nazov_UNIQUE` (`nazov` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizza` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(255) NOT NULL,
  `popis` TEXT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `obrazok_url` VARCHAR(2048) NULL,
  `aktivna` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nazov_UNIQUE` (`nazov` ASC) ,
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizza_Velkost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizza_Velkost` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Pizza_ID` BIGINT UNSIGNED NOT NULL,
  `nazov_velkosti` VARCHAR(50) NOT NULL,
  `cena` DECIMAL(10,2) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_Pizza_Velkost_Pizza_idx` (`Pizza_ID` ASC) ,
  CONSTRAINT `fk_Pizza_Velkost_Pizza`
    FOREIGN KEY (`Pizza_ID`)
    REFERENCES `Pizzeria`.`Pizza` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Ingrediencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Ingrediencia` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(255) NOT NULL,
  `alergen` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Tag` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nazov_UNIQUE` (`nazov` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Objednavka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Objednavka` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Pouzivatel_ID` BIGINT UNSIGNED NOT NULL, 
  `kuchar_id` BIGINT UNSIGNED NULL,       
  `kurier_id` BIGINT UNSIGNED NULL,       
  `stav` VARCHAR(50) NOT NULL,
  `celkova_cena` DECIMAL(10,2) UNSIGNED NOT NULL,
  `adresa` VARCHAR(500) NOT NULL,
  `poznamka` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_Objednavka_Pouzivatel1_idx` (`Pouzivatel_ID` ASC),
  INDEX `fk_Objednavka_Kuchar_idx` (`kuchar_id` ASC),
  INDEX `fk_Objednavka_Kurier_idx` (`kurier_id` ASC),
  CONSTRAINT `fk_Objednavka_Pouzivatel1`
    FOREIGN KEY (`Pouzivatel_ID`)
    REFERENCES `Pizzeria`.`Pouzivatel` (`ID`),
  CONSTRAINT `fk_Objednavka_Kuchar`
    FOREIGN KEY (`kuchar_id`)
    REFERENCES `Pizzeria`.`Pouzivatel` (`ID`),
  CONSTRAINT `fk_Objednavka_Kurier`
    FOREIGN KEY (`kurier_id`)
    REFERENCES `Pizzeria`.`Pouzivatel` (`ID`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Polozka_Kosika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Polozka_Kosika` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Pouzivatel_ID` BIGINT UNSIGNED NOT NULL,
  `Pizza_Velkost_ID` BIGINT UNSIGNED NOT NULL,
  `mnozstvo` INT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_Polozka_Kosika_Pouzivatel1_idx` (`Pouzivatel_ID` ASC) ,
  INDEX `fk_Polozka_Kosika_Pizza_Velkost1_idx` (`Pizza_Velkost_ID` ASC) ,
  CONSTRAINT `fk_Polozka_Kosika_Pouzivatel1`
    FOREIGN KEY (`Pouzivatel_ID`)
    REFERENCES `Pizzeria`.`Pouzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Polozka_Kosika_Pizza_Velkost1`
    FOREIGN KEY (`Pizza_Velkost_ID`)
    REFERENCES `Pizzeria`.`Pizza_Velkost` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Polozka_Objednavky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Polozka_Objednavky` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Objednavka_ID` BIGINT UNSIGNED NOT NULL,
  `mnozstvo` INT UNSIGNED NOT NULL,
  `archivny_nazov` VARCHAR(255) NOT NULL,
  `archivna_cena` DECIMAL(10,2) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_Polozka_Objednavky_Objednavka1_idx` (`Objednavka_ID` ASC) ,
  CONSTRAINT `fk_Polozka_Objednavky_Objednavka1`
    FOREIGN KEY (`Objednavka_ID`)
    REFERENCES `Pizzeria`.`Objednavka` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pouzivatel_Roly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pouzivatel_Roly` (
  `Rola_ID` BIGINT UNSIGNED NOT NULL,
  `Pouzivatel_ID` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Rola_ID`, `Pouzivatel_ID`),
  INDEX `fk_Rola_has_Pouzivatel_Pouzivatel1_idx` (`Pouzivatel_ID` ASC) ,
  INDEX `fk_Rola_has_Pouzivatel_Rola1_idx` (`Rola_ID` ASC) ,
  CONSTRAINT `fk_Rola_has_Pouzivatel_Rola1`
    FOREIGN KEY (`Rola_ID`)
    REFERENCES `Pizzeria`.`Rola` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rola_has_Pouzivatel_Pouzivatel1`
    FOREIGN KEY (`Pouzivatel_ID`)
    REFERENCES `Pizzeria`.`Pouzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizza_Ingrediencie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizza_Ingrediencie` (
  `Pizza_ID` BIGINT UNSIGNED NOT NULL,
  `Ingrediencia_ID` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Pizza_ID`, `Ingrediencia_ID`),
  INDEX `fk_Pizza_has_Ingrediencia_Ingrediencia1_idx` (`Ingrediencia_ID` ASC) ,
  INDEX `fk_Pizza_has_Ingrediencia_Pizza1_idx` (`Pizza_ID` ASC) ,
  CONSTRAINT `fk_Pizza_has_Ingrediencia_Pizza1`
    FOREIGN KEY (`Pizza_ID`)
    REFERENCES `Pizzeria`.`Pizza` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_has_Ingrediencia_Ingrediencia1`
    FOREIGN KEY (`Ingrediencia_ID`)
    REFERENCES `Pizzeria`.`Ingrediencia` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizza_Tagy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizza_Tagy` (
  `Tag_ID` BIGINT UNSIGNED NOT NULL,
  `Pizza_ID` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Tag_ID`, `Pizza_ID`),
  INDEX `fk_Tag_has_Pizza_Pizza1_idx` (`Pizza_ID` ASC) ,
  INDEX `fk_Tag_has_Pizza_Tag1_idx` (`Tag_ID` ASC) ,
  CONSTRAINT `fk_Tag_has_Pizza_Tag1`
    FOREIGN KEY (`Tag_ID`)
    REFERENCES `Pizzeria`.`Tag` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tag_has_Pizza_Pizza1`
    FOREIGN KEY (`Pizza_ID`)
    REFERENCES `Pizzeria`.`Pizza` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
