-- MySQL Script generated by MySQL Workbench
-- Thu Dec 25 04:51:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`Pouzivatel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pouzivatel` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `meno` VARCHAR(100) NOT NULL,
  `priezvisko` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `heslo` VARCHAR(255) NOT NULL,
  `telefon` VARCHAR(20) NOT NULL,
  `aktivny` TINYINT(1) NOT NULL DEFAULT 1,
  `obrazok_url` VARCHAR(2048) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Rola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Rola` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nazov_UNIQUE` (`nazov` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizza` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(255) NOT NULL,
  `popis` TEXT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `obrazok_url` VARCHAR(2048) NULL,
  `aktivna` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nazov_UNIQUE` (`nazov` ASC) ,
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizza_Velkost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizza_Velkost` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Pizza_ID` BIGINT UNSIGNED NOT NULL,
  `nazov_velkosti` VARCHAR(50) NOT NULL,
  `cena` DECIMAL(10,2) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_Pizza_Velkost_Pizza_idx` (`Pizza_ID` ASC) ,
  CONSTRAINT `fk_Pizza_Velkost_Pizza`
    FOREIGN KEY (`Pizza_ID`)
    REFERENCES `Pizzeria`.`Pizza` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Ingrediencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Ingrediencia` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(255) NOT NULL,
  `alergen` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Tag` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nazov_UNIQUE` (`nazov` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Objednavka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Objednavka` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Pouzivatel_ID` BIGINT UNSIGNED NOT NULL, 
  `kuchar_id` BIGINT UNSIGNED NULL,       
  `kurier_id` BIGINT UNSIGNED NULL,       
  `stav` VARCHAR(50) NOT NULL,
  `celkova_cena` DECIMAL(10,2) UNSIGNED NOT NULL,
  `adresa` VARCHAR(500) NOT NULL,
  `poznamka` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_Objednavka_Pouzivatel1_idx` (`Pouzivatel_ID` ASC),
  INDEX `fk_Objednavka_Kuchar_idx` (`kuchar_id` ASC),
  INDEX `fk_Objednavka_Kurier_idx` (`kurier_id` ASC),
  CONSTRAINT `fk_Objednavka_Pouzivatel1`
    FOREIGN KEY (`Pouzivatel_ID`)
    REFERENCES `Pizzeria`.`Pouzivatel` (`ID`),
  CONSTRAINT `fk_Objednavka_Kuchar`
    FOREIGN KEY (`kuchar_id`)
    REFERENCES `Pizzeria`.`Pouzivatel` (`ID`),
  CONSTRAINT `fk_Objednavka_Kurier`
    FOREIGN KEY (`kurier_id`)
    REFERENCES `Pizzeria`.`Pouzivatel` (`ID`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Polozka_Kosika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Polozka_Kosika` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Pouzivatel_ID` BIGINT UNSIGNED NOT NULL,
  `Pizza_Velkost_ID` BIGINT UNSIGNED NOT NULL,
  `mnozstvo` INT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_Polozka_Kosika_Pouzivatel1_idx` (`Pouzivatel_ID` ASC) ,
  INDEX `fk_Polozka_Kosika_Pizza_Velkost1_idx` (`Pizza_Velkost_ID` ASC) ,
  CONSTRAINT `fk_Polozka_Kosika_Pouzivatel1`
    FOREIGN KEY (`Pouzivatel_ID`)
    REFERENCES `Pizzeria`.`Pouzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Polozka_Kosika_Pizza_Velkost1`
    FOREIGN KEY (`Pizza_Velkost_ID`)
    REFERENCES `Pizzeria`.`Pizza_Velkost` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Polozka_Objednavky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Polozka_Objednavky` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Objednavka_ID` BIGINT UNSIGNED NOT NULL,
  `mnozstvo` INT UNSIGNED NOT NULL,
  `archivny_nazov` VARCHAR(255) NOT NULL,
  `archivna_cena` DECIMAL(10,2) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_Polozka_Objednavky_Objednavka1_idx` (`Objednavka_ID` ASC) ,
  CONSTRAINT `fk_Polozka_Objednavky_Objednavka1`
    FOREIGN KEY (`Objednavka_ID`)
    REFERENCES `Pizzeria`.`Objednavka` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pouzivatel_Roly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pouzivatel_Roly` (
  `Rola_ID` BIGINT UNSIGNED NOT NULL,
  `Pouzivatel_ID` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Rola_ID`, `Pouzivatel_ID`),
  INDEX `fk_Rola_has_Pouzivatel_Pouzivatel1_idx` (`Pouzivatel_ID` ASC) ,
  INDEX `fk_Rola_has_Pouzivatel_Rola1_idx` (`Rola_ID` ASC) ,
  CONSTRAINT `fk_Rola_has_Pouzivatel_Rola1`
    FOREIGN KEY (`Rola_ID`)
    REFERENCES `Pizzeria`.`Rola` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rola_has_Pouzivatel_Pouzivatel1`
    FOREIGN KEY (`Pouzivatel_ID`)
    REFERENCES `Pizzeria`.`Pouzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizza_Ingrediencie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizza_Ingrediencie` (
  `Pizza_ID` BIGINT UNSIGNED NOT NULL,
  `Ingrediencia_ID` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Pizza_ID`, `Ingrediencia_ID`),
  INDEX `fk_Pizza_has_Ingrediencia_Ingrediencia1_idx` (`Ingrediencia_ID` ASC) ,
  INDEX `fk_Pizza_has_Ingrediencia_Pizza1_idx` (`Pizza_ID` ASC) ,
  CONSTRAINT `fk_Pizza_has_Ingrediencia_Pizza1`
    FOREIGN KEY (`Pizza_ID`)
    REFERENCES `Pizzeria`.`Pizza` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_has_Ingrediencia_Ingrediencia1`
    FOREIGN KEY (`Ingrediencia_ID`)
    REFERENCES `Pizzeria`.`Ingrediencia` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizza_Tagy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizza_Tagy` (
  `Tag_ID` BIGINT UNSIGNED NOT NULL,
  `Pizza_ID` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Tag_ID`, `Pizza_ID`),
  INDEX `fk_Tag_has_Pizza_Pizza1_idx` (`Pizza_ID` ASC) ,
  INDEX `fk_Tag_has_Pizza_Tag1_idx` (`Tag_ID` ASC) ,
  CONSTRAINT `fk_Tag_has_Pizza_Tag1`
    FOREIGN KEY (`Tag_ID`)
    REFERENCES `Pizzeria`.`Tag` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tag_has_Pizza_Pizza1`
    FOREIGN KEY (`Pizza_ID`)
    REFERENCES `Pizzeria`.`Pizza` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE `Pizzeria`;

-- "123456789Password"
INSERT INTO Pouzivatel (meno, priezvisko, email, heslo, telefon, obrazok_url) 
VALUES ('Liubym', 'Naval', 'admin@gmail.sk', '$2a$10$jZJjE6jzXZMtAgGKN9VZH.VCCJpzwsXh0kGZDxlrQ9tRzvPEugEYq', '+421901234567','/uploads/User.jpg');
INSERT INTO Pouzivatel (meno, priezvisko, email, heslo, telefon, obrazok_url) 
VALUES 
('Peter', 'Kuchár', 'kuchar@gmail.sk', '$2a$10$jZJjE6jzXZMtAgGKN9VZH.VCCJpzwsXh0kGZDxlrQ9tRzvPEugEYq', '+421902111222','/uploads/User.jpg'),
('Michal', 'Kuriér', 'kurier@gmail.sk', '$2a$10$jZJjE6jzXZMtAgGKN9VZH.VCCJpzwsXh0kGZDxlrQ9tRzvPEugEYq', '+421903333444','/uploads/User.jpg');

INSERT INTO Rola (nazov) VALUES ('ROLE_ZAKAZNIK'), ('ROLE_KUCHAR'), ('ROLE_KURIER'), ('ROLE_ADMIN');

INSERT INTO Pouzivatel_Roly (Pouzivatel_ID, Rola_ID) VALUES (1, 4); -- ADMIN
INSERT INTO Pouzivatel_Roly (Pouzivatel_ID, Rola_ID) VALUES (2, 2), (3, 3);

INSERT INTO Tag (nazov) VALUES ('Pikantné'), ('Vegetariánske'), ('Novinka'), ('Bezlepkové'), ('Najpredávanejšie');

INSERT INTO Pizza (nazov, popis, slug, obrazok_url, aktivna) VALUES 
('Capricciosa', 'Paradajkový základ, mozzarella, šunka, šampiňóny, olivy, artičoky', 'capricciosa', '/uploads/capricciosa.webp', 1),
('Carbonara', 'Smotanový základ, mozzarella, slanina, vajce, čierne korenie', 'carbonara', '/uploads/carbonara-pizza.webp', 1),
('Delicatezza Rustica', 'Paradajky, mozzarella, prosciutto, rukola, sušené paradajky, olivy', 'delicatezza-rustica', '/uploads/delicatezza-rustica.webp', 1),
('Diavola Piccante', 'Pikantný základ, mozzarella, talianska saláma, feferóny, kukurica', 'diavola', '/uploads/diavola-piccante.webp', 1),
('Funghi', 'Paradajkový základ, mozzarella, čerstvé šampiňóny', 'funghi', '/uploads/funghi.webp', 1),
('Funghi al Panna', 'Smotanový základ, mozzarella, šampiňóny, čerstvý špenát', 'funghi-al-panna', '/uploads/funghi-al-panna.webp', 1),
('Gluten-free Primavera', 'Bezlepkové cesto, zeleninová zmes, cuketa, paprika, cibuľa, rukola', 'primavera-gf', '/uploads/gluten-free-primavera.webp', 1),
('Hawaii Classic', 'Paradajkový základ, mozzarella, šunka, sladký ananás', 'hawaii', '/uploads/hawaii-classic.webp', 1),
('La Crema Bianca', 'Smotanový základ, výber talianskych syrov, bazalkové pesto', 'crema-bianca', '/uploads/la-crema-bianca.webp', 1),
('Margherita Classica', 'Tradičný paradajkový základ, mozzarella, čerstvá bazalka, olivový olej', 'margherita', '/uploads/margherita-classica.webp', 1);

-- 1. Capricciosa
INSERT INTO Pizza_Velkost (Pizza_ID, nazov_velkosti, cena) VALUES (1, '33cm', 8.90), (1, '40cm', 11.50), (1, '50cm', 15.90);
-- 2. Carbonara
INSERT INTO Pizza_Velkost (Pizza_ID, nazov_velkosti, cena) VALUES (2, '33cm', 9.20), (2, '40cm', 12.00), (2, '50cm', 16.50);
-- 3. Delicatezza Rustica
INSERT INTO Pizza_Velkost (Pizza_ID, nazov_velkosti, cena) VALUES (3, '33cm', 10.50), (3, '40cm', 13.50), (3, '50cm', 18.00);
-- 4. Diavola Piccante
INSERT INTO Pizza_Velkost (Pizza_ID, nazov_velkosti, cena) VALUES (4, '33cm', 9.50), (4, '40cm', 12.50), (4, '50cm', 16.90);
-- 5. Funghi
INSERT INTO Pizza_Velkost (Pizza_ID, nazov_velkosti, cena) VALUES (5, '33cm', 7.90), (5, '40cm', 10.50), (5, '50cm', 14.50);
-- 6. Funghi al Panna
INSERT INTO Pizza_Velkost (Pizza_ID, nazov_velkosti, cena) VALUES (6, '33cm', 8.50), (6, '40cm', 11.20), (6, '50cm', 15.20);
-- 7. Gluten-free Primavera
INSERT INTO Pizza_Velkost (Pizza_ID, nazov_velkosti, cena) VALUES (7, '33cm', 11.00), (7, '40cm', 14.00), (7, '50cm', 18.50);
-- 8. Hawaii Classic
INSERT INTO Pizza_Velkost (Pizza_ID, nazov_velkosti, cena) VALUES (8, '33cm', 8.70), (8, '40cm', 11.40), (8, '50cm', 15.60);
-- 9. La Crema Bianca
INSERT INTO Pizza_Velkost (Pizza_ID, nazov_velkosti, cena) VALUES (9, '33cm', 9.80), (9, '40cm', 12.80), (9, '50cm', 17.20);
-- 10. Margherita Classica
INSERT INTO Pizza_Velkost (Pizza_ID, nazov_velkosti, cena) VALUES (10, '33cm', 6.90), (10, '40cm', 9.50), (10, '50cm', 13.00);

INSERT INTO Ingrediencia (nazov, alergen) VALUES 
('Paradajkový základ', NULL), ('Smotanový základ', 'A7'), ('Mozzarella', 'A7'), 
('Šunka', NULL), ('Šampiňóny', NULL), ('Slanina', NULL), 
('Vajce', 'A3'), ('Prosciutto', NULL), ('Rukola', NULL), 
('Sušené paradajky', NULL), ('Olivy', NULL), ('Artičoky', NULL), 
('Pikantná saláma', NULL), ('Feferóny', NULL), ('Špenát', NULL), 
('Bezlepkové cesto', NULL), ('Ananás', NULL), ('Bazalka', NULL);

INSERT INTO Pizza_Tagy (Tag_ID, Pizza_ID) VALUES 
(1, 4), -- Diavola -> Pikantné
(2, 10), -- Margherita -> Vegetariánske
(2, 5), -- Funghi -> Vegetariánske
(4, 7), -- Primavera -> Bezlepkové
(3, 3), -- Delicatezza -> Novinka
(5, 10), -- Margherita -> Najpredávanejšie
(5, 8); -- Hawaii -> Najpredávanejšie

-- 1. Capricciosa
INSERT INTO Pizza_Ingrediencie (Pizza_ID, Ingrediencia_ID) VALUES (1, 1), (1, 3), (1, 4), (1, 5), (1, 11), (1, 12);
-- 2. Carbonara
INSERT INTO Pizza_Ingrediencie (Pizza_ID, Ingrediencia_ID) VALUES (2, 2), (2, 3), (2, 6), (2, 7);
-- 3. Delicatezza Rustica
INSERT INTO Pizza_Ingrediencie (Pizza_ID, Ingrediencia_ID) VALUES (3, 1), (3, 3), (3, 8), (3, 9), (3, 10), (3, 11);
-- 4. Diavola Piccante
INSERT INTO Pizza_Ingrediencie (Pizza_ID, Ingrediencia_ID) VALUES (4, 1), (4, 3), (4, 13), (4, 14);
-- 5. Funghi
INSERT INTO Pizza_Ingrediencie (Pizza_ID, Ingrediencia_ID) VALUES (5, 1), (5, 3), (5, 5);
-- 6. Funghi al Panna
INSERT INTO Pizza_Ingrediencie (Pizza_ID, Ingrediencia_ID) VALUES (6, 2), (6, 3), (6, 5), (6, 15);
-- 7. Gluten-free Primavera
INSERT INTO Pizza_Ingrediencie (Pizza_ID, Ingrediencia_ID) VALUES (7, 16), (7, 9), (7, 15);
-- 8. Hawaii Classic
INSERT INTO Pizza_Ingrediencie (Pizza_ID, Ingrediencia_ID) VALUES (8, 1), (8, 3), (8, 4), (8, 17);
-- 9. La Crema Bianca
INSERT INTO Pizza_Ingrediencie (Pizza_ID, Ingrediencia_ID) VALUES (9, 2), (9, 3), (9, 18);
-- 10. Margherita Classica
INSERT INTO Pizza_Ingrediencie (Pizza_ID, Ingrediencia_ID) VALUES (10, 1), (10, 3), (10, 18);

INSERT INTO Objednavka (Pouzivatel_ID, kuchar_id, kurier_id, stav, celkova_cena, adresa, poznamka) VALUES 
(1, 2, 3, 'DORUCENA', 24.10, 'Hlavná 15, Nitra', 'Doručiť k zadnému vchodu'),
(1, 2, 3, 'DORUCUJE_SA', 15.90, 'Štefánikova 2, Nitra', 'Nechajte pred dverami'),
(1, 2, NULL, 'PRIPRAVENA', 11.20, 'Akademická 1, Nitra', 'Bez cibule prosím'),
(1, 2, NULL, 'PRIPRAVUJE_SA', 31.80, 'Mostná 4, Nitra', NULL),
(1, NULL, NULL, 'CAKAJUCA', 8.50, 'Farská 10, Nitra', 'Volajte vopred');

INSERT INTO Polozka_Objednavky (Objednavka_ID, mnozstvo, archivny_nazov, archivna_cena) VALUES 
(1, 2, 'Capricciosa 33cm', 8.90), 
(1, 1, 'Margherita Classica 50cm', 13.00),
(2, 1, 'Carbonara 40cm', 12.00),
(3, 1, 'Diavola Piccante 33cm', 9.50),
(4, 2, 'Hawaii Classic 50cm', 15.60),
(5, 1, 'Funghi 33cm', 7.90);